sudo: required
language: generic

services:
        - docker

before_install:
        - docker build -t vintagesteel/FrontEnd -f Dockerfile.dev .

script:
        - docker run -e CI=true vintagesteel/FrontEnd npm run test
