
version: '3'
services:
        web:
                build: .
                ports:
                    - "3080:3000"
                volumes:
                   - /app/node_modules
                   - .:/app
 web:
        stdin_open: true
